# Generated by Django 5.2.5 on 2025-08-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='backend_type',
            field=models.CharField(choices=[('SCH', 'Schema'), ('DB', 'Database')], max_length=3),
        ),
    ]
