# Generated by Django 5.2.5 on 2025-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_patient_alter_hospital_backend_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
