# Generated by Django 5.2.5 on 2025-08-15 06:05

import django_omnitenant.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_hospital_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='backend_type',
            new_name='isolation_type',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='tenant_id',
            field=models.SlugField(help_text='Must be a valid DNS label (RFC 1034/1035).', unique=True, validators=[django_omnitenant.validators.validate_dns_label]),
        ),
    ]
