# Generated by Django 5.2.5 on 2025-08-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_backend_type_hospital_isolation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Backend-specific configuration or metadata, such as connection strings.'),
        ),
    ]
