# Generated by Django 5.2.5 on 2025-08-15 12:24

import django.db.models.deletion
import django_omnitenant.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_hospital_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.SlugField(help_text='Must be a valid DNS label (RFC 1034/1035).', unique=True, validators=[django_omnitenant.validators.validate_dns_label])),
                ('tenant', models.OneToOneField(help_text='The tenant this domain belongs to.', on_delete=django.db.models.deletion.CASCADE, to='demo.hospital')),
            ],
            options={
                'abstract': False,
                'unique_together': {('tenant', 'domain')},
            },
        ),
    ]
